### ISSUE TITLE
elvish: should default to `edit:complete-filename` if no match is found by carapace

### ISSUE THREAD

**Issue by AlexanderBrevig** [rsteube/carapace#543]
Currently, a lot of the completers feel broken in `elvish` because it prints an error if `carapace` cannot find a completion.

Simple example:

```elvish
# navigate to carapace git project
hx action.go # nake some changes
# check changes
git diff a<TAB>
```

Expected: autocomplete to `action`, then a new tab will show:
```elvish
 COMPLETING argument  
action.go  action_test.go
```

This would happen if the snippet defaults to `edit:complete-filename` if `carapace` fails the match:

https://github.com/rsteube/carapace/blob/e961a1d209980f253febf405dfdd63ded9786b8c/internal/shell/elvish/snippet.go#L12-L21

**Comment by rsteube** [comment]
Not having a file completion fallback is intentional.

The approach in carapace is to explicitly configure all completion options (where possible) so if carapace does not return something the command should not accept a file anyway.

There are certainly some exceptions at the moment due to the limited support for non-posix commands.
HIghly dynamic commands like git can also make completions quite hard so these can be strongly opiniated at some point.

For `git diff` file completion for dash args (`git diff <REF> -- <FILE>`) was already configured but not yet for standard args (it indeed accepts that).

For cases like this i tend to use a [check for file path prefix](https://pkg.go.dev/github.com/rsteube/carapace-bin@v0.13.4/pkg/util#HasPathPrefix).
So it defaults to refs but completes files when the word has a path prefix.

**Comment by AlexanderBrevig** [comment]
`git diff --az<TAB>` works, thanks for answering!

I understand the motivation behind it too. Awesome project BTW!
